apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Event service
  S3_EVENT_BUCKET_NAME: "event-banner-tickety-2026-uor-e23"
  BANNER_IMAGE_MAX_BYTES: "5242880"
  JSON_BODY_LIMIT: "10mb"
  # Artist service
  S3_ARTIST_BUCKET_NAME: "artist-profile-image-tickety-2026-uor-e23"
  PROFILE_IMAGE_MAX_BYTES: "5242880"