apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXT_PUBLIC_EVENT_SERVICE_URL: "http://44.194.213.136:32399/api/events"
  NEXT_PUBLIC_USER_SERVICE_URL: "http://44.194.213.136:32399/api/users"
  NEXT_PUBLIC_BOOKING_SERVICE_URL: "http://44.194.213.136:32399/api/bookings"
  NEXT_PUBLIC_ARTIST_SERVICE_URL: "http://44.194.213.136:32399/api/artists"
  NEXT_PUBLIC_VENUE_SERVICE_URL: "http://44.194.213.136:32399/api/venues"
  NEXT_PUBLIC_PAYMENT_SERVICE_URL: "http://44.194.213.136:32399/api/payments"
  NEXT_PUBLIC_INVENTORY_SERVICE_URL: "http://44.194.213.136:32399/api/inventory"
