apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "MyNewPass123!"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:

  DATABASE_URL_ARTIST:    "mongodb://mongodb-service:27017/event_platform_artist_db"
  DATABASE_URL_USER:      "mongodb://mongodb-service:27017/event_platform_user_db"
  DATABASE_URL_VENUE:     "mongodb://mongodb-service:27017/event_platform_venue_db"

  DATABASE_URL_ARTIST:  "mysql://root:MyNewPass123%21@mysql-service:3306/event_platform_artist_db"
  DATABASE_URL_EVENT:   "mysql://root:MyNewPass123%21@mysql-service:3306/event_platform_event_db"
  DATABASE_URL_PAYMENT: "mysql://root:MyNewPass123%21@mysql-service:3306/event_platform_payment_db"
  DATABASE_URL_TICKET:  "mysql://root:MyNewPass123%21@mysql-service:3306/event_platform_ticket_db"
  DATABASE_URL_USER:    "mysql://root:MyNewPass123%21@mysql-service:3306/event_platform_user_db"
  DATABASE_URL_VENUE:   "mysql://root:MyNewPass123%21@mysql-service:3306/event_platform_venue_db"
  JWT_SECRET:           "replace-with-a-strong-secret"
